config/routes.rb
Rails.application.routes.draw do
  root to: 'weather_forecasts#index'
  get :find_weather, controller: :weather_forecasts, action: :find_weather
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/weather_forecast.rb
class WeatherForecast
  attr_accessor :country_name, :city_name, :temperature, :description, :icon,
                :sys_type, :wind_speed, :humidity, :pressure, :lat, :lon

  def initialize(weather_data)
    @city_name =  weather_data['name'].presence || 'Unknown'
    @country_name = weather_data['sys']['country'].presence || 'Unknown'
    @sys_type = weather_data['sys']['type']
    @temperature = KelvinToCelsius.call(kelvin: weather_data['main']['temp']).celsius
    @wind_speed = weather_data['wind']['speed']
    @humidity = weather_data['main']['humidity']
    @pressure = weather_data['main']['pressure']
    @lat = weather_data['coord']['lat']
    @lon = weather_data['coord']['lon']
    weather = weather_data['weather'].first
    if weather.present?
      @description = weather['description']
      @icon = weather['icon']
    end
  end

  class << self
    def random_cities(num_cities = nil)
      WeatherOfRandomCities.call(num_cities: num_cities).random_weathers
    end

    def find_by_city_and_country(city_name, country_code)
      FindWeatherByCity.call(city: city_name, country: country_code).current_weather
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :show_flash

  private

  def show_flash
    flash.now[:notice] = "Found the about page!" if request.path == '/pages/about'
  end
end

app/controllers/weather_forecasts_controller.rb
class WeatherForecastsController < ApplicationController
  def index
    @current_weathers = WeatherForecast.random_cities
  end

  def find_weather
    begin
      @current_weather = WeatherForecast.find_by_city_and_country(search_params[:city], search_params[:country])
      raise if @current_weather.blank?
    rescue
      redirect_to root_path, flash: { error: "Your inputs couldn't be found" }
    end
  end

  private

  def search_params
    params.permit(:city, :country)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Weather Forecasts" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : 'Weather Forecasts' %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <main role="main">
       <%= yield %>
    </main>
  </body>
</html>

app/views/weather_forecasts/_form.html.erb
<%= form_tag(find_weather_path, method: :get) do %>
    <%= text_field_tag :city, params[:city], {placeholder: 'City Name'} %>
    <%= text_field_tag :country, params[:country], {placeholder: 'Country Code'} %>
    <%= submit_tag 'Search' %>
<% end %>

app/views/weather_forecasts/_weather_wedgit.html.erb
<div class="widget-right weather-right--type<%= weather_info.sys_type%> widget-right--brown">
  <div class="widget-right__header widget-right__header--brown">
    <div class="widget-right__layout">
      <h2 class="widget-right__title"><%= weather_info.city_name%>, <%= weather_info.country_name%></h2>
      <p class="widget-right__description"><%= weather_info.description%></p>
    </div>
    <img src="http://openweathermap.org/themes/openweathermap/assets/vendor/owm/img/widgets/<%= weather_info.icon%>.png" width="128" height="128" alt="Weather in <%= weather_info.city_name%>, <%= weather_info.country_name%>" class="weather-right__icon weather-right__icon--type<%= weather_info.sys_type%>" data-pin-nopin="true">
  </div>
  <div class="weather-right weather-right--brown">
    <div class="weather-right__layout">
      <div class="weather-right__temperature"><%= weather_info.temperature%><span>°C</span></div>
      <div class="weather-right__weather">
        <div class="weather-right-card">
          <table class="weather-right__table">
            <tbody>
            <tr class="weather-right__items">
              <th colspan="2" class="weather-right__item">Details</th>
            </tr>
            <tr class="weather-right__items">
              <td class="weather-right__item">Feels like</td>
              <td class="weather-right__item weather-right__feels"><%= weather_info.temperature%><span>°C</span></td>
            </tr>
            <tr class="weather-right__items">
              <td class="weather-right__item">Wind</td>
              <td class="weather-right__item weather-right__wind-speed"><%= weather_info.wind_speed%> m/s</td>
            </tr>
            <tr class="weather-right-card__items">
              <td class="weather-right__item">Humidity</td>
              <td class="weather-right__item weather-right__humidity"><%= weather_info.humidity%>%</td>
            </tr>
            <tr class="weather-right-card__items">
              <td class="weather-right__item">Pressure</td>
              <td class="weather-right__item weather-right__pressure"><%= weather_info.pressure%> hPa</td>
            </tr>
            <tr class="weather-right-card__items">
              <td class="weather-right__item">lat</td>
              <td class="weather-right__item weather-right__pressure"><%= weather_info.lat%></td>
            </tr>
            <tr class="weather-right-card__items">
              <td class="weather-right__item">lon</td>
              <td class="weather-right__item weather-right__pressure"><%= weather_info.lon%></td>
            </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="widget-right__footer widget-right__footer--brown">
    <div class="widget-right__layout">
      <a href="http://openweathermap.org/" target="_blank" class="widget-right__link">OpenWeatherMap</a>
      <div class="widget-right__date"><%= Time.now.strftime('%H:%M')%></div>
    </div>
  </div>
</div>

app/views/weather_forecasts/find_weather.html.erb
<h2>Weather in <%= @current_weather.city_name%>, <%= @current_weather.country_name%></h2>
<%= render 'form'%>
</br>
<%= render partial: 'weather_wedgit', locals: {weather_info: @current_weather}%>

app/views/weather_forecasts/index.html.erb
<h2>Random Forecasts</h2>
<% if flash[:error] %>
    <div class="alert alert-danger" role="alert">
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
      <%= flash[:error] %>
    </div>
<% end %>

<%= render 'form' %>
</br>
<% @current_weathers.each do |weather_info| %>
    <%= render partial: 'weather_wedgit', locals: {weather_info: weather_info} %>
    </br>
<% end %>